# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - mlopsemotion

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mlopsemotion.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_b3bfe933f14442bca97999f29be011a8 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_eb4d2a8e6f084299957bcaa6bcbfed94 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mlopsemotion.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b3bfe933f14442bca97999f29be011a8 }}/mlopsemotion1:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mlopsemotion'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_004558fc53ae4fd6898bb5e05bc83c58 }}
        images: 'mlopsemotion.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b3bfe933f14442bca97999f29be011a8 }}/mlopsemotion1:${{ github.sha }}'